/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cassini' at '01.01.16 22:18' with Gradle 2.9
 *
 * @author cassini, @date 01.01.16 22:18
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
